ALTER TABLE pages ADD COLUMN show_in_menu INTEGER NOT NULL DEFAULT 1;
ALTER TABLE pages ADD COLUMN show_on_site INTEGER NOT NULL DEFAULT 1;
ALTER TABLE pages ADD COLUMN menu_group TEXT NOT NULL DEFAULT '';
